version: "3.8"

volumes:
  postgres-data:

services:
  app:
    container_name: nestjs_shims
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity